
server:
  port: 8080

spring:
  application:
    name: API-gateway
  cloud:
    gateway:
      routes:
        - id: email-service
          uri: http://localhost:8084
          predicates:
            - Path=/email/**
        - id: order-service
          uri: http://localhost:8083
#          uri: lb://order-service
          predicates:
            - Path=/api/orders/** , /orders/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway, routes, health
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
